[project]
name = "airtable"
dynamic = ["version"]
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "keboola.component==1.4.4",
    "keboola.utils",
    "keboola.http-client",
    "mock~=4.0.3",
    "freezegun~=1.2",
    "requests==2.33.0",
    "kbcstorage==0.7.2",
    "dataconf==2.4.0",
    "pyhocon==0.3.59",
]

[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | build
  | dist
  | data
)/
'''

[dependency-groups]
dev = [
    "black>=25.9.0",
    "flake8>=7.3.0",
    "ruff>=0.13.3",
]
